### ISSUE TITLE
Fetch joined *ToMany's of an in PC-existing entity don't get merged

### ISSUE THREAD

**Issue by beikov** [datanucleus/datanucleus-core#189] opened 2017-03-01 11:20 UTC
Imagine the following entities

```java
@Entity
@Inheritance(strategy = InheritanceType.JOINED)
public class EventField {
    
    @Id
    Long id;
    String name;
    @ManyToOne(fetch = FetchType.LAZY)
    UserField user;
}

@Entity
@Inheritance(strategy = InheritanceType.JOINED)
public class UserField {
    
    @Id
    Long id;
    String name;
    @OneToMany(cascade = CascadeType.ALL)
    Set<UserField> users = new HashSet<>();
}

@Entity
public class SuperUserField extends UserField {
    
    String privilege;
}
```

and the following simple data

```java
        SuperUserField su = new SuperUserField(1L, "Super user");
        su.getUsers().add(new UserField(2L, "User"));
        em.persist(su);
        
        em.persist(new EventField(1L, "Event 1", su));
```

If I have an uninitialized entity in the persistence context

```java
UserField userProxy = em.find(EventField.class, 1L).getUser();
// alternatively do this
// UserField userProxy = em.getReference(UserField.class, 1L);
```

and later join fetch a relation(*users* in this case) of that object

```java
List<EventField> events = em.createQuery("SELECT e FROM EventField e JOIN FETCH e.user u LEFT JOIN FETCH u.users", EventField.class).getResultList();
```

the basic properties of the object are _populated_ by the objects fetched by that query, but not the collection *users*.
IMO the following should be possible

```java
// Close the entity manager since we don't want lazy loading
em.close();
assertEquals(1, userProxy.getUsers().size());
```

But accessing the collection results in

```
java.lang.IllegalAccessException: You have just attempted to access property "users" yet this property was not detached when you detached the object. Either dont access this property, or detach it when detaching the object.
```

**Comment by andyjefferson** [comment] 2017-03-01 16:19
You mean "all fields specified with JOIN FETCH don't always get loaded and hence don't get detached"; there is no merging involved.

This is because the RDBMS plugin only currently supports "1-N bulk fetch" on the immediate neighbour of the candidate (and you have the level after here). So it treats the FETCH JOIN as a hint only for those cases currently.

**Comment by beikov** [comment] 2017-03-01 16:35
Essentially yes. From what I saw in the debugging, the `userProxy` was uninitialized at first, but after the query, the _basic attributes_ got populated. The only thing did not get populated is the collection `users`.

**Comment by andyjefferson** [comment] 2017-04-08 13:01
Closing this as won't fix since the problem is RDBMS specific (other store plugins would handle that fine due to how the relations are stored). Refer to rdbms-170 to track this

**Closed by andyjefferson** 2017-04-08 13:01 UTC
